Method.Directive.delegateName  ::= "delegateName"
Method.Directive.extends       ::= "extends"
Method.Directive.external      ::= "external"
Method.Directive.isAbstract    ::= "isAbstract"
Method.Directive.isAttribute   ::= "isAttribute"
Method.Directive.isClassMethod ::= "isClassMethod"
Method.Directive.isGuarded     ::= "isGuarded"
Method.Directive.isPakage      ::= "isPackage"
Method.Directive.isPrivate     ::= "isPrivate"
Method.Directive.isProtected   ::= "isProtected"
Method.Directive.method        ::= "method"
Method.Directive.methodEquals  ::= "method" "=" method
Method.Directive.name          ::= "name"
Method.Directive.overrides     ::= "overrides"