
Driver.emit ::= "emit(" string ")"

Driver.epilog ::= "epilog"

Driver.new ::= "new(" options. "," output  ")"

Driver.prolog ::= "prolog"

Driver.say ::= "say(" string ")"

Driver.startLine ::= "startLine(" lineNo ")"

Driver.tags2highlight ::= "tags2highlight(" tags "," extra ")"