Element.category ::= "category"

Element.from ::= "from"

Element.isAssigned ::= "isAssigned"

Element.isIgnorable ::= "isIgnorable"

Element.less ::= element "<" categories

Element.lessless ::= element "<<" subcategories

Element.makeIgnorable ::= "makeIgnorable"

Element.next ::= "next"

Element.notless ::= element "\<" categories

Element.notlessless ::= element "\<<" subcategories

Element.parts ::= "parts"

Element.prev ::= "prev"

Element.setAssigned ::= "setAssigned"

Element.source ::= "source"

Element.subCategory ::= "subCategory"

Element.to ::= "to"

Element.value ::= "value"
